// ARQUIVO GERADO - não edite à mão.
// Gerado por wms-api/scripts/gerar-padrao-front.js a partir do catálogo de
// permissões da API (wms-api/lib/permissoes.js). Chave da permissão -> cargos
// que têm essa permissão por padrão (o administrador sempre tem tudo).
// Só é usado como reserva quando a API não manda a lista de permissões.
export const PADRAO_PERMISSOES = {
    'dash.mapa': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.produtos': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.unidades': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.entradas_manuais': ["recebimento_reposicao"],
    'dash.reposicao_kanban': ["recebimento_reposicao"],
    'dash.estoque_pulmao': ["recebimento_reposicao"],
    'dash.controle_lote': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.pedidos': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.divergencias': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.historico': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.relatorios': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'dash.colaboradores': ["recebimento_reposicao"],
    'dash.perfis_fiscais': [],
    'dash.perfis_separacao': [],
    'dash.acessos': [],
    'col.imprimir_ordem': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'col.separacao': ["picking"],
    'col.inventario': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'col.picking': ["recebimento_reposicao"],
    'col.nf_importacao': ["recebimento_reposicao"],
    'col.nf_devolucao': ["recebimento_reposicao"],
    'col.conferencia': ["conferente","picking"],
    'col.reimprimir': ["recebimento_reposicao"],
    'col.pulmao': ["recebimento_reposicao"],
    'col.transferencia': ["recebimento_reposicao"],
    'col.estoque_devolucao': ["recebimento_reposicao"],
    'produtos.editar': ["conferente","picking","recebimento_reposicao"],
    'produtos.excluir': ["conferente","picking","recebimento_reposicao"],
    'unidades.editar': ["conferente","picking","recebimento_reposicao"],
    'unidades.excluir': ["conferente","picking","recebimento_reposicao"],
    'mapa.editar': ["conferente","picking","recebimento_reposicao"],
    'mapa.remover_pallet': ["conferente","picking","recebimento_reposicao"],
    'inventario.contar': ["conferente","picking","recebimento_reposicao"],
    'inventario.gerenciar': ["conferente","picking","recebimento_reposicao"],
    'recebimento.iniciar': ["recebimento_reposicao"],
    'recebimento.editar': ["conferente","picking","recebimento_reposicao"],
    'nf_importacao.receber': ["recebimento_reposicao"],
    'nf_importacao.editar': ["conferente","picking","recebimento_reposicao"],
    'nf_devolucao.receber': ["recebimento_reposicao"],
    'nf_devolucao.perfis_fiscais': [],
    'nf_devolucao.debug': [],
    'nf_devolucao.editar': ["conferente","picking","recebimento_reposicao"],
    'devolucao_estoque.operar': ["recebimento_reposicao"],
    'devolucao_estoque.editar': ["conferente","picking","recebimento_reposicao"],
    'transferencia.operar': ["recebimento_reposicao"],
    'transferencia.editar': ["conferente","picking","recebimento_reposicao"],
    'separacao.operar': ["picking"],
    'separacao.imprimir': ["conferente","picking","recebimento_reposicao"],
    'separacao.perfis': [],
    'separacao.correcoes': [],
    'separacao.editar': ["conferente","picking","recebimento_reposicao"],
    'conferencia.operar': ["conferente","picking"],
    'conferencia.editar': ["conferente","picking","recebimento_reposicao"],
    'tarefas.separacao_confirmar': ["picking"],
    'tarefas.reposicao': ["recebimento_reposicao"],
    'tarefas.editar': ["conferente","picking","recebimento_reposicao"],
    'picking.repor': ["recebimento_reposicao"],
    'picking.editar': ["conferente","picking","recebimento_reposicao"],
    'pulmao.transferir': ["recebimento_reposicao"],
    'pulmao.teste': ["recebimento_reposicao"],
    'pulmao.editar': ["conferente","picking","recebimento_reposicao"],
    'fluxos.editar': ["conferente","picking","recebimento_reposicao"],
    'relatorios.executar': ["conferente","picking","recebimento_reposicao","engenharia_produtos"],
    'colaboradores.gerenciar': ["recebimento_reposicao"],
    'acessos.gerenciar': [],
    'sistema.manutencao': [],
};
