// Rotas do fluxo novo de Separacao (substitui o antigo por item).
// Cada passo dispara uma chamada real pro ZenERP, usando o
// reservation_id e outgoing_list_id ja sincronizados na tabela
// pedidos. O progresso fica salvo em pedidos.etapa_separacao.
//
// Ordem dos passos (numeracao igual a combinada com o usuario):
// 2. iniciar-reserva      -> reservationOpStart
// 3. alocar-estoque       -> reservationOpAllocateAuto (operador bipa aqui)
// 6. foto                 -> so nosso sistema, entre 3 e 4
// 4. finalizar-reserva    -> reservationOpFinish (exige foto ja salva)
// 5. finalizar-romaneio   -> outgoingListOpPacked
// 7. definir-volume       -> outgoingListOpVolumeCreateAuto
// 8. (etiqueta de volume, so front-end, sem rota propria aqui)
// 9. fora do escopo por agora (liberar nota pra faturamento)
const express = require('express');
const pool = require('../db');
const { zenErpPost } = require('../poller');

const router = express.Router();

async function buscarPedido(pedidoId) {
    const { rows } = await pool.query(
            `SELECT id, numero_erp, reservation_id, outgoing_list_id, etapa_separacao,
                            foto_separacao_base64, volume_id, volume_quantidade
                                     FROM pedidos WHERE id = $1`,
                                             [pedidoId]
                                                 );
                                                     return rows[0] || null;
                                                     }

                                                     // GET /separacao-erp/fila
                                                     // Lista pedidos que ainda nao terminaram a separacao (qualquer
                                                     // etapa antes de volume_definido), do mais antigo pro mais novo.
                                                     router.get('/fila', async (req, res) => {
                                                         try {
                                                                 const { rows } = await pool.query(`
                                                                             SELECT id, numero_erp, reservation_id, outgoing_list_id, etapa_separacao, criado_em
                                                                                         FROM pedidos
                                                                                                     WHERE etapa_separacao IS DISTINCT FROM 'volume_definido'
                                                                                                                   AND reservation_id IS NOT NULL
                                                                                                                                 AND outgoing_list_id IS NOT NULL
                                                                                                                                             ORDER BY criado_em ASC
                                                                                                                                                     `);
                                                                                                                                                             res.json(rows);
                                                                                                                                                                 } catch (erro) {
                                                                                                                                                                         console.error(erro);
                                                                                                                                                                                 res.status(500).json({ erro: 'Falha ao consultar fila de separacao' });
                                                                                                                                                                                     }
                                                                                                                                                                                     });
                                                                                                                                                                                     
                                                                                                                                                                                     // GET /separacao-erp/:pedidoId
                                                                                                                                                                                     router.get('/:pedidoId', async (req, res) => {
                                                                                                                                                                                         try {
                                                                                                                                                                                                 const pedido = await buscarPedido(req.params.pedidoId);
                                                                                                                                                                                                         if (!pedido) {
                                                                                                                                                                                                                     return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                     res.json(pedido);
                                                                                                                                                                                                                                         } catch (erro) {
                                                                                                                                                                                                                                                 console.error(erro);
                                                                                                                                                                                                                                                         res.status(500).json({ erro: 'Falha ao consultar pedido' });
                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                             // POST /separacao-erp/:pedidoId/iniciar-reserva
                                                                                                                                                                                                                                                             router.post('/:pedidoId/iniciar-reserva', async (req, res) => {
                                                                                                                                                                                                                                                                 try {
                                                                                                                                                                                                                                                                         const pedido = await buscarPedido(req.params.pedidoId);
                                                                                                                                                                                                                                                                                 if (!pedido) {
                                                                                                                                                                                                                                                                                             return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                             if (!pedido.reservation_id) {
                                                                                                                                                                                                                                                                                                                         return res.status(400).json({ erro: 'Esse pedido nao tem reservation_id sincronizado ainda' });
                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                         await zenErpPost(`/material/reservationOpStart/${pedido.reservation_id}`, {});
                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                 await pool.query(`UPDATE pedidos SET etapa_separacao = 'reserva_iniciada' WHERE id = $1`, [pedido.id]);
                                                                                                                                                                                                                                                                                                                                                         res.json({ status: 'reserva_iniciada' });
                                                                                                                                                                                                                                                                                                                                                             } catch (erro) {
                                                                                                                                                                                                                                                                                                                                                                     console.error(erro?.response?.data || erro);
                                                                                                                                                                                                                                                                                                                                                                             res.status(502).json({ erro: 'Falha ao iniciar reserva no ZenERP', detalhe: erro?.response?.data });
                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                 // POST /separacao-erp/:pedidoId/alocar-estoque
                                                                                                                                                                                                                                                                                                                                                                                 router.post('/:pedidoId/alocar-estoque', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                                                             const pedido = await buscarPedido(req.params.pedidoId);
                                                                                                                                                                                                                                                                                                                                                                                                     if (!pedido) {
                                                                                                                                                                                                                                                                                                                                                                                                                 return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                 await zenErpPost(`/material/reservationOpAllocateAuto/${pedido.reservation_id}`, {});
                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                         await pool.query(`UPDATE pedidos SET etapa_separacao = 'estoque_alocado' WHERE id = $1`, [pedido.id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                 res.json({ status: 'estoque_alocado' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (erro) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                             console.error(erro?.response?.data || erro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     res.status(502).json({ erro: 'Falha ao alocar estoque no ZenERP', detalhe: erro?.response?.data });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // POST /separacao-erp/:pedidoId/foto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Body: { fotoBase64 } - foto unica por Ordem de Separacao, tirada
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // depois de alocar estoque e antes de finalizar a reserva.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         router.post('/:pedidoId/foto', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const { fotoBase64 } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (!fotoBase64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return res.status(400).json({ erro: 'Informe fotoBase64' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const { rowCount } = await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     `UPDATE pedidos SET foto_separacao_base64 = $2 WHERE id = $1`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [req.params.pedidoId, fotoBase64]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (rowCount === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             res.json({ status: 'foto_salva' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (erro) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.error(erro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 res.status(500).json({ erro: 'Falha ao salvar foto' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // POST /separacao-erp/:pedidoId/finalizar-reserva
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     router.post('/:pedidoId/finalizar-reserva', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const pedido = await buscarPedido(req.params.pedidoId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!pedido) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!pedido.foto_separacao_base64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return res.status(400).json({ erro: 'Precisa tirar a foto de comprovacao antes de finalizar a reserva' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await zenErpPost(`/material/reservationOpFinish/${pedido.reservation_id}`, {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await pool.query(`UPDATE pedidos SET etapa_separacao = 'reserva_finalizada' WHERE id = $1`, [pedido.id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 res.json({ status: 'reserva_finalizada' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } catch (erro) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             console.error(erro?.response?.data || erro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     res.status(502).json({ erro: 'Falha ao finalizar reserva no ZenERP', detalhe: erro?.response?.data });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // POST /separacao-erp/:pedidoId/finalizar-romaneio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         router.post('/:pedidoId/finalizar-romaneio', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const pedido = await buscarPedido(req.params.pedidoId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!pedido) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await zenErpPost(`/material/outgoingListOpPacked/${pedido.outgoing_list_id}`, {});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await pool.query(`UPDATE pedidos SET etapa_separacao = 'romaneio_finalizado' WHERE id = $1`, [pedido.id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         res.json({ status: 'romaneio_finalizado' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (erro) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error(erro?.response?.data || erro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             res.status(502).json({ erro: 'Falha ao finalizar romaneio no ZenERP', detalhe: erro?.response?.data });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // POST /separacao-erp/:pedidoId/definir-volume
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Body: { quantidade }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 router.post('/:pedidoId/definir-volume', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const quantidade = Number(req.body?.quantidade) || 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const pedido = await buscarPedido(req.params.pedidoId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!pedido) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return res.status(404).json({ erro: 'Pedido nao encontrado' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const resposta = await zenErpPost(`/material/outgoingListOpVolumeCreateAuto/${pedido.outgoing_list_id}`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 quantity: quantidade,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const dados = resposta.data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const volumeId = Array.isArray(dados) ? dados[0]?.id ?? null : dados?.id ?? null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             `UPDATE pedidos SET etapa_separacao = 'volume_definido', volume_id = $2, volume_quantidade = $3 WHERE id = $1`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [pedido.id, volumeId, quantidade]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         res.json({ status: 'volume_definido', volumeId, quantidade });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (erro) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error(erro?.response?.data || erro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             res.status(502).json({ erro: 'Falha ao definir volume no ZenERP', detalhe: erro?.response?.data });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 module.exports = router;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
